### PR TITLE
Merge OSD file format V2 updates

### PR DESCRIPTION
**Pull request by benlumley**
The comprises the changes to the OSD overlay tool from last week; we'd like to get MSP-OSD v0.12.2 released; which breaks compatibility with the OSD overlay tool that is live currently. So we'd like to get this released.

This also includes a change/fix from j005u; have checked in with him on discord...

"it may or may not help with step 5 stability, but in any case it's harmless. so yeah, include it."

The one issue; I added a new translation string; which we won't have translations for. But we figure this working with a missing translation trumps this not working and not missing translations.

### CODE REVIEW

**Comment by benlumley** [comment]
Just saw #421 after opening this - I'll run through that process later on!

**Comment by stylesuxx** [comment]
That step 5 fix is already in develop. I'd change the base branch for this PR to go against develop and things should be fine. #421 is just a checklist for the new release.

**Comment by benlumley** [comment]
Anything I can do to push this along / make your life easier ? 

Do shout!

**Comment by stylesuxx** [comment]
@benlumley Thank you - I just deployed it, could you do me a favor and check on prod that everything is working as it is supposed to?

**Comment by benlumley** [comment]
Looks good!

**Comment by stylesuxx** [comment]
Whoop, whoop - thanks for checking!

**Pull request merged**
