### PR TITLE
OSD Overlay create a MP4 clip much longer than the original

### LINKED ISSUE #392: OSD Overlay create a MP4 clip much longer than the original
### Device

Goggles V2

### Operating System (Including version)

Windows 11

### Browser

Chrome

### Trace ID (bottom left of the configurator screen)

75e9a36d-b0ee-4833-a697-ca1981bb4aee

### Describe the issue

When the MP4 is rendered & played in VLC media player it runs correctly and ends at 6min & 21sec which is correct. But when mouse hovering over the file the length is reported to be 22min & 54sec.

When then trying to place the file in a timeline in Davinci Resolve the file is reported to be "Offline" & the time line is 22min & 54sec... this means that no editing can be done.

Something appears to go wrong when the rendered OSD-MP4 gets closed.

Attaching the exif info for the file from ExifTool where the track length is reported to be 22min & 55sec.

[DJIG0000-osd.txt](https://github.com/fpv-wtf/wtfos-configurator/files/11962311/DJIG0000-osd.txt)

### PR DESCRIPTION
**Pull request by FinalFrag**
This PR fixes #392 OSD Overlay create a MP4 clip much longer than the original

### CODE REVIEW

**Comment by stylesuxx** [comment]
exiftool will still show "truncated data" with this patch?

**Comment by FinalFrag** [comment]
Yes, I have no idea what is causing that. All I changed was the duration of the clip.

**Comment by stylesuxx** [comment]
I see. But if this has no other side effects, it is much more preferable than the status quo. in this case I will just add an issue to track this.

**Review by stylesuxx — APPROVED** [review]

**Comment by FinalFrag** [comment]
Not as far as I can tell.

If I have the time, I want to look into just using ffmpeg to overlay the osd images instead of the whole frame by frame thing and reconstructing the output video we do now. There are so many magic numbers and string involved in the current approach.

Ffmpeg is a cleaner approach, if successful...

**Comment by stylesuxx** [comment]
So you would instead render on the goggles themselves? The current approach is to keep it device agnostic.

But it would definitely be cool to get this going on the device. I was initially thinking about a gstreamer plugin that just merges osd file and video source. Looking forward to your ffpmeg solution though.

Merged - thanks again for your contribution, very much appreciated!
Let me know when you are done with your current "roll", then I'll prepare a new release with all the bugfixes.

**Comment by j005u** [comment]
@FinalFrag there's some python code https://github.com/Knifa/osd-dump-tools with ffmpeg and a fancier cmdline tool https://github.com/shellixyz/hd_fpv_video_tool and a few others that I can't find links for immediately.

The reason we went for WebCodecs despite it being a bit of a clusterf*ck in more way than one was to have GPU acceleration in the browser.

I'm not sure if that's what you were proposing, but there's not enough grunt on the goggles to add the osd natively.

**Pull request merged**
