### PR TITLE
Add an Expand page, link to repository and provide some info on how t…

### PR DESCRIPTION
**Pull request by stylesuxx**
…o contribute. #90

### CODE REVIEW

**Comment by j005u** [comment]
I would put the contents of the expand page before the buttons on either the wtfos page or even on the main page (if kept short and sweet). Also, it would probably look a bit better on a material ui card?

I would keep the new main tile slot for a Wiki link once we've re-organized that a bit. I put a card for it on the wtfos project board.

Feel free to borrow any text from the wtfos README: https://github.com/fpv-wtf/wtfos

Or I can take it upon myself to write it, but after I've finished with wtfos-package-config.

**Comment by stylesuxx** [comment]
Makes sense. I think I would prefer to have it on the main page then - will adapt it accordingly.

**Comment by stylesuxx** [comment]
@j005u refactored to show on the top of the main page.

**Comment by j005u** [comment]
Let's change the last paragraph to "You can find mode details in our README." linking to https://github.com/fpv-wtf and move the whole text block above the connect button and warning banner.

**Pull request merged**
